### ISSUE TITLE
Final tweaks before RR signs-off

### ISSUE THREAD

**Issue by jezpete** [ThreeSixtyGiving/Insights#103]
- [x] X axis angled labels on most bar charts are obscured / not showing properly
- [ ] Replace "360Giving InsightsBeta" at top of results screens with "360Insights".
- [x] In the note to the location chart, add a full stop between registers and Mapping
- [x] Latest income chart - x axis labels to not imply double counting. So the second bar would be £10k - £99k, etc
- [x] Where the charts have had their labels amended to not imply double counting, can that also be reflected in the filters? Otherwise poss anomalies 
- [x] In the what next, feedback, add full stop after the email address and start "You could share what you’ve learned with...." on a new line
- [ ]

**Comment by drkane** [comment]
All done.

I personally think the income band ones look weird with the new labels. I can see that we're no longer suggesting double counting (although that's not applicable to charity income where very few charities ever have income exactly on the boundaries), but we've now introduced gaps in the labels (it's ambiguous where a charity of £10,500 income would go). It's also inconsistent with other ways the data is presented, eg the ncvo almanac.

**Comment by jezpete** [comment]
Thanks. I'll see what Rachel wants to do about this. 
Please can you amend the name on the top of results page to 360Insights

**Comment by morchickit** [comment]
It's actually not true to say 99K, because it needs then to be 99,999, so I agree with David here.

**Comment by drkane** [comment]
We have come to an arrangement! closing this now...
