### ISSUE TITLE
Names of funders cut off in chart 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/Insights#115]
When uploading a dataset with multiple funders, the name of grantmakers cutoff. 
See screenshot 
![image](https://user-images.githubusercontent.com/3273659/53801909-59462b00-3f38-11e9-9daf-1c01595ae219.png)

**Comment by drkane** [comment]
![image](https://user-images.githubusercontent.com/1049910/55419209-2a899780-556c-11e9-82a1-e142e24de401.png)

I think this is now fixed
