### ISSUE TITLE
Registry file(s) not loading

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/Insights#119]
Spirit of 2012 doesn't load with the updated url - is the next step to check with the publisher if access settings can be changed? 

Virgin Money Foundation have also reported that their file doesn't load - from the error message it doesn't look quite the same as Spirit/Dundee issue.

**Comment by KDuerden** [comment]
Co-op group's csv also won't load. It has an error which I think is the same as Virgin Money - also a CSV publisher 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 3825: invalid start byte
Is a work around getting a different version of CSV?

**Comment by KDuerden** [comment]
I saved the two problematic csv files with UTF8 encoding error - they were actually ANSI - and I was able to get them to work. 
I can ask the publishers if they are able to update their files. I'm assuming there won't be any technical reason why they can't use UTF8.

**Comment by drkane** [comment]
Should be fixed through this update: https://github.com/drkane/threesixty-parser/commit/0bce04c4b9d36575e3d2c2b326c445b665e5447d (nb not yet updated on the live site)

**Comment by KDuerden** [comment]
Local Trust file is getting error on loading via list and upload method.

**Comment by drkane** [comment]
Thanks @KDuerden - I've opened a separate issue for that one: #125
