### ISSUE TITLE
What happens when a file is updated?

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#123]
Describe the process - check how it's decided to use a cached or non-cached version of file

**Comment by drkane** [comment]
File is cached (forever?) based on the file id.

The file id for files fetched from URLs is based on the URL of the request, plus either the [`Etag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) or [`Last-Modified`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) header from the HTTP request for the file.

When either the URL, ETag or Last-Modified value is change, the fileid will be different so the cache won't be used.

**Comment by drkane** [comment]
@KDuerden

**Comment by KDuerden** [comment]
Are etag or last modified metadata or are these things that the publisher updates?
