### ISSUE TITLE
registry update command doesn't skip cache

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#127]
The command [`flask registry update --skip-cache`](https://github.com/ThreeSixtyGiving/Insights/blob/master/tsg_insights/commands/registry.py#L9-L17) should load the latest version of the registry file, ignoring anything in the cache. This doesn't seem to be working - it is still loading an old version of the file.

I think this may be an underlying issue with [`get_registry`](https://github.com/ThreeSixtyGiving/Insights/blob/master/tsg_insights/data/registry.py#L14-L25) as it didn't work when this function was run manually anyway.

**Comment by morchickit** [comment]
Is this something Open Data Services needs to know?

**Comment by drkane** [comment]
@morchickit - this isn't, but there might be something in terms of validating the aggregates that are included in the registry JSON.

Closing as was fixed in dev version of site which is now pushed to live. https://github.com/ThreeSixtyGiving/Insights/commit/8c0c23c2f81af49ae3367a01e65682429018981c#diff-e810913b73df05ee8bb25987520e08b7R23
