### ISSUE TITLE
GDPR - ask users whether they want to keep the files or not

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#15]

**Comment by KDuerden** [comment]
Can you explain further? 
Asking a user if they want to save results/a session?
A publisher whether their data file should be stored?
How is personal data involved? Session cookies? 
For the tool in general we should use the privacy notices from CoVE and GrantNav and adapt to fit - eg https://dataquality.threesixtygiving.org/terms/

**Comment by drkane** [comment]
There's now a data privacy notice when uploading - this needs to be reviewed.

**Comment by KDuerden** [comment]
On beta version I tested yesterday, once a file is uploaded, I can't see how someone with the url could access the source file. If the source data isn't accessible and the results are all aggregated then the GDPR implications are what data is stored in the server, and what kind of access is possible there (and why).

The wording for CoVE t&c will be useful: https://dataquality.threesixtygiving.org/terms/
The relevant bit is **Data uploaded to this website** section onwards. 
However CoVE allows anyone with the results url to download the original data or a converted version, so there are GDPR implications of sharing the links. Does Insights do this too? 
If not, then the privacy notice only needs to focus on server-side access wording and cookies notice info.

**Comment by drkane** [comment]
Hi @KDuerden - On accessing a source file, there's an outstanding action to allow users to do this (#35).

If this does happen then it would be possible to see the whole file (including the data about organisations that has been added), but you would also get any personal data included - eg if they had accidentally included people's names in the recipient field.

I'm personally still happy to go ahead with #35 on the basis that the right form of words in the statement should cover us.

>However CoVE allows anyone with the results url to download the original data or a converted version, so there are GDPR implications of sharing the links. Does Insights do this too?

Yes - I'll look at the wording from CoVE

**Comment by KDuerden** [comment]
Additionally we have this text, which is an FAQ style answer: 
Is the Data Quality Tool secure?
The Data Quality tool has been designed to support people when they are preparing their data, meaning the data inputted into it is in varying stages of readiness. The feedback report you receive has a private URL which means only those with the link can access the page and the data. If your data is not suitable for sharing publicly then you should treat this URL with care and only share it with people who are allowed access to the data. If this URL is not linked to from public pages it will not be possible for people to come across it by accident.

There are further details about how the files are stored, and deleted automatically after 7 days. Click on the ‘More Information’ section on the home page of the tool: https://dataquality.threesixtygiving.org/

**Comment by drkane** [comment]
About page added: http://insightsbeta.findthatcharity.uk/about

**Comment by KDuerden** [comment]
Thanks for this. 
The single column format for the text makes it quite difficult to read, is that something you can change?
I'll review the text properly later and in context of the file upload text.

**Comment by KDuerden** [comment]
Can I have details of what cookies will be used on the site, and their functions?
The site will need a cookie permission pop-up.
Our overall privacy policy states that our individual sites have their own privacy and cookie notices, so we should split the privacy/cookie info from the about page into it's own one. I'll draft this based on GN/CoVE and then we can slot in the specific cookie details.

**Comment by KDuerden** [comment]
For this notice I also need to know how long uploaded files will be saved on the server / accessible to users with the url.

**Comment by KDuerden** [comment]
Suggested wording for 'Drop your file here' box.

Privacy notice: 
Please ensure that you have the appropriate permissions to upload data into 360 Insights. 
Do not submit confidential or non-public personal data to this tool. 
Read the 360 Insights privacy notice for further information [hyperlink].
