### ISSUE TITLE
Branding/look and feel

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#24]
- [x] 360Giving - no space
- [x] **D**ata **E**xplorer - capitals
- [x] When more than 5 funders - show number of funders instead
- [x] Add favicons
- [x] add context to the top of front page
- [x] move logo to left hand side
- [x] style title so similar to http://data.threesixtygiving.org/
- [x] Copy footer from https://www.threesixtygiving.org/
- [x] Change background colour to match threesixtygiving.org/ (see [comment](https://github.com/ThreeSixtyGiving/explorer/issues/24#issuecomment-429852750))
- [x] Change the name - working title "360Giving Insights"
- [x] Centered circle graphic for loading screen
- [x] Look at whether "pause" and "cancel" buttons can be hidden from file upload box
- [x] remove plotly dash "undo" button
- [x] labs@threesixtygiving.org - feedback link

**Comment by drkane** [comment]
Show number of grants for each chart

**Comment by drkane** [comment]
Style for background:

```
background: -webkit-linear-gradient(top, #EDFEFF 0%, #fff 600px);
background: linear-gradient(to bottom, #EDFEFF 0%, #fff 600px);
```

**Comment by jezpete** [comment]
Branding and presentation: 

An Insights variation of the 360Giving logo on top left (for interim just use existing 360Giving logo)

Copy positioned centrally top: 

Welcome. 
Discover grantmaking insights by uploading or selecting a file that meets the 360Giving Standard [link https://www.threesixtygiving.org/support/standard/]. 

This 360Giving Insights tool will check the data for recipients with charity or company numbers and combine extra data about them. It will also add data based on the postcode of the recipients.

Copy for below the functionality:

360Giving Insights is in Beta. We would love your feedback on what works well and less well. Please email us [mailto:labs@threesixtygiving.org]

Footer as per core site, adapted as appropriate. 

Can the results page have all the above changes too (except the copy)?
