### ISSUE TITLE
Add next steps for grantmakers 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/Insights#3]
Mor and David to compile a list of 3 next steps / tools for grantmakers to explore with their data.

**Comment by morchickit** [comment]
See databasics.io example - https://databasic.io/en/wtfcsv/results/5b73338c9dfb0a00e15f07ff

**Comment by drkane** [comment]
An idea for this:

---

# What next?

## 1. Make the most of your data

`(nb only shown depending on the fields included)`

Grants data is at its most powerful when you can link it to other datasets. There were some pieces missing from the data which meant we couldn't make the most of it. For linkable data, we suggest adding:

 - external organisation identifiers, like charity numbers (`<link to guidance>`)
 - postcodes or other geo data (`<link to guidance>` - nb the site doesn't currently use all the recipient geo data, so this could be misleading)

## 2. Try other services and get inspiration

There are lots of other services you can use to explore and visualise this kind of data. Here are some of our favourites

- flourish
- databasic
- carto
- 360Giving visualisations

## 3. Do you own analysis

You can also download the original files to analyse yourself, for example in Excel or another package. The download includes all the additional information we've added to our data, like charity data or geo data from the postcodes.

**Comment by morchickit** [comment]
I like this text!
@jezpete - you can copy edit it when you are back.

**Comment by jezpete** [comment]
Thanks. Here's my edit:

# What next?
## 1. Make the most of your data
`(nb only shown depending on the fields included)`

Grants data is at its most powerful when you can link it to other datasets. There were some pieces missing from the data you selected which meant we couldn't make the most of it. For linkable data, we suggest adding:

* external organisation identifiers, like charity numbers (`<link to guidance>`)
* postcodes or other geo data (`<link to guidance>` - nb the site doesn't currently use all the recipient geo data, so this could be misleading)

## 2. Try other services and get inspiration
There are lots of other services you can use to explore and visualise this kind of data. Here are some of our favourites

* Flourish https://flourish.studio/
* Databasic https://databasic.io/en/
* Carto https://carto.com/
* 360Giving visualisations https://www.threesixtygiving.org/2018/09/21/revealing-the-bigger-picture/

## 3. Do your own analysis
You can also download the data generated by 360Insights to analyse yourself, for example in Excel or another software. The download includes all the additional information we've added to our data, like charity data or geo data from the postcodes. 

@drkane where will the download buttons be in relation to this box? The text in ##3 can refer to them?

**Comment by claudioccm** [comment]
@drkane styles here: https://github.com/ccmdesign/360-insights/commit/8e4f2b5c7d654ed5ffaebd81f1d470c3061cf8ca

**Comment by KDuerden** [comment]
# What next?
## 1. Make the most of your data
`(nb only shown depending on the fields included)`

Grants data is at its most powerful when you can link it to other datasets. There were some pieces missing from the data you selected which meant we couldn't make the most of it. For linkable data, we suggest adding, wherever possible:

* external organisation identifiers, like charity numbers
* postcodes or other geo data

## 2. Try other services and get inspiration
There are lots of other services you can use to explore and visualise this kind of data. Here are some of our favourites

* Flourish https://flourish.studio/
* Databasic https://databasic.io/en/
* Carto https://carto.com/
* 360Giving visualisations https://www.threesixtygiving.org/2018/09/21/revealing-the-bigger-picture/

## 3. Do your own analysis
You can also download the data generated by 360Insights to analyse yourself, for example in Excel or another software. The download includes all the additional information we've added to the data, like charity data or geo data from the postcodes.

minor edits above
@morchickit @drkane 
What is the intended destination for the guidance links? The Standard docs on org IDs is a bit technical, and there isn't anything for specifically for geo data. We're creating more accessible publisher guidance about both of these as part of the CoVE update but that won't be ready until end March.

**Comment by morchickit** [comment]
@KDuerden - I made tiny markdown changes to the links. 
I think we will have to link to the documentation of the standard about IDs for now. 
We can always change it and add guidance as we have them. 
We can also add a support mail for more info?

**Comment by KDuerden** [comment]
Yes, good idea

**Comment by morchickit** [comment]
@jezpete - I edited @KDuerden latest version and added a feedback line there. See if it's ok? Connect to #90
