### ISSUE TITLE
Add ability to download amended files

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#35]

**Comment by morchickit** [comment]
Do you mean the version with the added fields?

**Comment by drkane** [comment]
> Do you mean the version with the added fields?

Yes - it should now work, but needs a link adding to the dashboard page

**Comment by drkane** [comment]
This is implemented (files are available at `/file/<fileid>:<format>`) but the link isn't shown anywhere.

**Comment by morchickit** [comment]
Do we need to add it to Claudio's work?

**Comment by drkane** [comment]
I don't think so - it just needs to be a link at the bottom so we can use the existing styles
