### ISSUE TITLE
Can't upload big files

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/Insights#46]
Insights can't deal with very big files (like Lloyds Bank Foundation), can we increase memory or time so it would not get "time out" message?

**Comment by drkane** [comment]
See also #42

**Comment by drkane** [comment]
Lloyd's should now be possible with the new updates. I think it's probably best for us to pre-load the biggest 20ish funders, as they do take a long time to load.

This can now be done through the command line directly on the server.

**Comment by morchickit** [comment]
That's amazing David! Sounds like a good plan

**Comment by drkane** [comment]
Should we be showing the files (but make so you can't select them) or hiding them in the list?
