### ISSUE TITLE
Home page tagline and intro text

### ISSUE THREAD

**Issue by jezpete** [ThreeSixtyGiving/Insights#47]
Under the logo, the tagline and intro to read:

**See your grantmaking in new ways** [in burgundy?]
Combine and visualise 360Giving, charity and other data to answer questions about your grantmaking

Thanks

**Comment by jezpete** [comment]
Thanks David. Please can you replace the "DISCOVER Grantmaking Insights" with "See your grantmaking in new ways" (and remove that from the body, which will now start with "Combine and visualise...").

**Comment by drkane** [comment]
Putting the "see your grantmaking in new ways" up there looks a bit odd imo, partly because of the line spacing:

![screenshot_2019-02-12 360giving insights](https://user-images.githubusercontent.com/1049910/52633657-03441180-2ebd-11e9-9c2c-a77df694cce4.png)

**Comment by jezpete** [comment]
Agree. Can it be smaller, and burgundy?

**Comment by jezpete** [comment]
See your grantmaking
in new ways

**Comment by drkane** [comment]
Have made this change - I still think it looks a bit odd:

![image](https://user-images.githubusercontent.com/1049910/52715949-9d778880-2f95-11e9-9623-504ed37a2b44.png)

**Comment by drkane** [comment]
1ddbae8be4bb79c6e6d3846d7a8fbcc9854efe75
