### ISSUE TITLE
Hero graphic

### ISSUE THREAD

**Issue by jezpete** [ThreeSixtyGiving/Insights#57]
For Claudio. Please remove the 3 'cogs' from the home page hero graphic.

**Comment by claudioccm** [comment]
@drkane and @jezpete - Here are the updated files. 

![hero](https://user-images.githubusercontent.com/1649373/52735483-c730af80-2f95-11e9-91b2-c668ffb6d5a1.jpg)
![hero](https://user-images.githubusercontent.com/1649373/52735484-c730af80-2f95-11e9-9337-78bc47c9c14c.png)

https://www.dropbox.com/s/phjyrtlnpsb1tr4/hero.svg?dl=0
