### ISSUE TITLE
Site does not show correctly on Windows 7 and Chrome or Explorer

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/Insights#65]
We got this image, but this also happens in narrow screens 
<img width="1101" alt="screen shot 2019-02-14 at 13 09 13" src="https://user-images.githubusercontent.com/3273659/52847277-a1c1b400-3103-11e9-99d7-f63315198ae4.png">

**Comment by claudioccm** [comment]
```
@media screen and (max-width: 1025px) {
  .homepage__header { 
    background-size: 50%; 
    text-align: center;
  }
}```
