### ISSUE TITLE
Select a new dataset

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/Insights#66]
Users reported that it is too faint and not noticeable. They mentioned it should take them back to datasets selection window, not hope page

**Comment by drkane** [comment]
Now opens window when clicked. Still needs styling.

**Comment by claudioccm** [comment]
```
/* kind of hacky this target solution. Ideally we would have a class for this button only. */

.results-page__menu > .results-page__menu__back {
  text-transform: uppercase;
  font-size: 1.1rem;
  color: white;
}```

**Comment by drkane** [comment]
Thanks @claudioccm - I can easily add classes to these items if that's helpful for adding styles.

**Comment by claudioccm** [comment]
@drkane awesome. yeah, basically replace this hacky selector by the class you add there. 
I use a simplified BEM naming convention to my CSS classes. [Here is an article ](https://medium.freecodecamp.org/how-to-better-organize-your-css-architecture-with-oocss-bem-smacss-65e8a5c207c0)I wrote about this, in case you are curious.
