### ISSUE TITLE
Region graph and map - postcode data from file vs from registered address

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/Insights#83]
Is the region chart and map taking the postcode from the charity data in preference to the postcode data included by the publisher, or vice versa?

**Comment by drkane** [comment]
Postcode from grants data first (from "Recipient Org:Postcode") then from the recipient org. 

Have you seen any odd results?

One task for the future is better integration of the beneficiary & recipient areas - at the moment these aren't used at all.

**Comment by KDuerden** [comment]
Not odd results but if that is the case the signposting needs to reflect the process better. I provided alternative wording when giving my feedback - eg

Chart based on postcodes found in the grant data, or the UK registered charity or company address, if postcodes are not available.

Map locations are based on postcodes found in the grant data, or the UK registered charity or company address, if postcodes are not available. Mapping is UK only.
