### ISSUE TITLE
Range of data included in 'download the results'

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/Insights#84]
The download the result file currently includes more data than is visualised on the Insights platform. 
I think it should mirror the charts more closely. 
The headers and content for anything not visualised might not make sense to users without some further explanation, especially the IMD and geodemographic data. 
Can this file be more curated/aligned to the current functionality of Insights.

**Comment by morchickit** [comment]
I think we can omit the following from the table:
- Recipient Org:0:Identifier:Scheme
- __org_charity_number
- __org_company_number
