### ISSUE TITLE
Copyedit and sign off of the about page content 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/Insights#88]
Text is here - https://docs.google.com/document/d/1T-wWB4CzCxVyXmu0dE0XeWqyRslgeIgKCTDWeLgrjDY/edit

**Comment by jezpete** [comment]
I've edited this copy in the Doc

**Comment by KDuerden** [comment]
As the about page includes privacy notice/cookie policy, final signoff awaiting confirmation of technical details - see #15 for details.

**Comment by drkane** [comment]
closing in favour of #15 - still to finalise cookies + cookie notice
