### ISSUE TITLE
Need to put link to About page on the homepage

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#91]
Not sure where it should go...

The links in the footer now point to appropriate parts of the about page, but I think we need a general one.

**Comment by morchickit** [comment]
I think it's OK for the launch to be at the footer, so taking it out of the milestone. Let's look at it when we get feedback?

**Comment by jezpete** [comment]
I don't see why we need an extra link on the home page. It's in the footer which is a large proportion of the home page! Ww should close this issue.
