### ISSUE TITLE
Remaining issues before launch

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#98]
- [x] Footer - remove "support", move "about" there instead
- [x] Footer - remove full stop from tag line
- [ ] Set up something that records homepage/dataset visits
- [x] Sentence case titles for charts - eg `Award date`
- [x] wording for postcode/region field - @jezpete to decide on wording
- [x] change what next text - @jezpete to finalise text
- [x] what next - support link should go to contact page

**Comment by jezpete** [comment]
Revised wording for Region/country field: "This chart is based on postcodes found in the grants data. If postcodes aren’t present, they are sourced from UK charity or company registers”

**Comment by jezpete** [comment]
About page amends needed:
- "Read the 360 Insights privacy notice for further information" link needs to be fixed - presumably to point at the anchor lower down the page
- Privacy, data controller, correct 360Giving
- Privacy, Rights, make them bullets, and not bold
- Privacy, add line space under the list of rights
- Privacy, purposes:  make them bullets, and not bold
- Privacy, traffic, insert relevant text
- Privacy, personal data: make them bullets, and not bold
- Privacy, add line space under the list of personal data
- Privacy, deleting: change 360 Insights to 360Insights 
- Terms and conditions. Where text is in UPPER CASE change to lower case, bold

**Comment by drkane** [comment]
Moved to #101
